site_name: peakipy
repo_url: https://github.com/j-brady/peakipy

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Instructions: instructions.md
  - Examples: examples.md
  - Lineshapes: lineshapes.md

theme:
  name: material
  palette:
    primary: green
    accent: indigo
  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - codehilite

extra_css:
    - css/termynal.css

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/termynal.js