site_name: peakipy
repo_url: https://github.com/j-brady/peakipy

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Instructions: instructions.md
  - Examples: examples.md
  - Lineshapes: lineshapes.md

#theme:
#  name: material
#  palette:
#    #primary: blue grey
#    #accent: indigo
#    scheme: peakipy

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - pymdownx.details
#  - codehilite

# extra_css:
# #  - css/termynal.css
#    - css/custom.css

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#  - js/termynal.js